import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {
    width: '100%',
    height: 250,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    marginBottom: 40,
    marginTop: 0,
    paddingTop: 0,
  },
  containerImg: {
    width: '100%',
    height: 210,
    marginBottom: 10,
    position: 'relative',
  },
  photo: {
    width: '100%',
    height: 210,
    resizeMode: 'contain',
    borderRadius: 4,
  },
  openHour: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    zIndex: 2,
    width: '35%',
    height: 37,
    borderRadius: 4,
    backgroundColor: '#D95F5A',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 0,
  },
  label: {
    fontFamily: 'CircularStd-Book',
    fontSize: 10,
    color: '#fff',
  },
  hour: {
    fontFamily: 'CircularStd-Bold',
    fontSize: 14,
    color: '#fff',
  },
  containerLike: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 2,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.9,
    shadowRadius: 13,
    elevation: 25,
  },
  description: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: '#EDECEC',
  },
  leftDescription: {
    width: '60%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  rightDescription: {
    width: '40%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  name: {
    fontFamily: 'CircularStd-Bold',
    fontSize: 18,
    color: '#343434',
    marginBottom: 5,
  },
  address: {
    fontFamily: 'CircularStd-Bold',
    fontSize: 10,
    color: '#A4A4A4',
  },
  stars: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginBottom: 5,
  },
  average: {
    fontFamily: 'CircularStd-Bold',
    fontSize: 15,
    color: '#343434',
  },
  location: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  miles: {
    fontFamily: 'CircularStd-Bold',
    fontSize: 12,
    color: '#A4A4A4',
  },
});
