import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  rightHeader: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  containerIcon: {
    position: 'relative',
    transform: [{rotate: '-30deg'}],
  },
  notification: {
    position: 'absolute',
    top: 1,
    right: -5,
    height: 6,
    width: 6,
    borderRadius: 3,
    backgroundColor: 'red',
  },
  borderPhoto: {
    marginLeft: 20,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.9,
    shadowRadius: 13,
    elevation: 25,
  },
  photo: {
    width: 50,
    height: 50,
    borderRadius: 4,
  },

  h1: {
    paddingHorizontal: 20,
    color: '#343434',
    fontFamily: 'CircularStd-Bold',
    fontSize: 28,
    marginBottom: 0,
  },
  h2: {
    paddingHorizontal: 16,
    color: '#343434',
    fontFamily: 'CircularStd-Book',
    fontSize: 26,
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  containerSearchInput: {
    paddingHorizontal: 20,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  containerInput: {
    width: '80 %',
    height: 50,
    borderRadius: 5,
    backgroundColor: '#f2f2f2',
    paddingHorizontal: 20,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
  },
  inputSearch: {
    width: '100%',
    fontFamily: 'CircularStd-Book',
    marginLeft: 5,
  },
  btnFilter: {
    width: 50,
    height: 50,
    borderRadius: 5,
    backgroundColor: '#D95F5A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerTags: {
    paddingHorizontal: 20,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  tag: {
    fontFamily: 'CircularStd-Book',
    fontSize: 16,
    color: '#A4A4A4',
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 4,
  },
  tagSelected: {
    fontFamily: 'CircularStd-Book',
    fontSize: 16,
    color: '#fff',
    backgroundColor: '#D95F5A',
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 4,
  },

  cards: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    width: '100%',
    backgroundColor: '#F3F3F3',
    paddingHorizontal: 20,
    paddingTop: 20,
  },
});
